<a href="https://colab.research.google.com/github/Abutunghe/Collaborations/blob/main/Sentinel_2_Classification_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML LULC Classification using Sentinel 2
This project deals the use of machine learning models including SVM, RF and KNN to classify the cocoa mosaic landscape in Western Ghana using Sentinel satellite images.

1) Connect to GEE, google drive

2) Load and filter sentinel 2 data to match WV2 site and date attributes

3) Load training and validation data from local drive

4) Classify S2 with SVM, RF, KNN and YOLO

5) Validate the classification results

## Part 1 - Preprocessing

### Connect GEE and drives

In [4]:
# Connect  and authenticate GEE
import ee

# Authenticate GEE
ee.Authenticate()

# Initailise GEE project
ee.Initialize(project='ee-abutunghem')

# Print a test message from the GEE servers
print(ee.String('Hello from the Earth Engine servers!').getInfo())


Hello from the Earth Engine servers!


**Connect to Google Drive**

In [5]:
# Connect Google Drive

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### Load ROI Data
Load ROI - vector data from GEE assests and local drive

In [6]:
# PhD study area - covers the entire western north and western south regions of Ghana
AOI = ee.FeatureCollection('projects/ee-abutunghem/assets/PhD/Study_Areas/WesternGhana')
#AOI.getInfo()

In [7]:
'''# Wordview study area
AOI2 = ee.FeatureCollection('projects/ee-abutunghem/assets/PhD/Study_Areas/WV2_AOI_for_S2')
AOI2.getInfo()
'''

"# Wordview study area\nAOI2 = ee.FeatureCollection('projects/ee-abutunghem/assets/PhD/Study_Areas/WV2_AOI_for_S2')\nAOI2.getInfo()\n"

In [8]:
'''# Alternatives - Load from local computer
from google.colab import files

print("Please upload all component files of your shapefile (e.g., .shp, .shx, .dbf, .prj):")
uploaded = files.upload()'''

'# Alternatives - Load from local computer\nfrom google.colab import files\n\nprint("Please upload all component files of your shapefile (e.g., .shp, .shx, .dbf, .prj):")\nuploaded = files.upload()'

### Load and filter Sentinel 2 collections
filter to match WV2 site and date attributes

In [18]:
# Load S2 data
sen2 = ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")  # Surface reflectance

#Load Cloud Score+ image collection, a product from Sentinel-2 Level 1C data that can be applied to either L1C or L2A collections.
csPlus = ee.ImageCollection('GOOGLE/CLOUD_SCORE_PLUS/V1/S2_HARMONIZED')

In [66]:
# Use 'cs (cloud score)' or 'cs_cdf' (cloud score - cumulative distribution function) bands
QA_BAND = 'cs_cdf' # Explicitly set QA_BAND
QA = 'cs' # Changed from 'cs' to 'cs_cdf' to match QA_BAND
threshold = 0.60

In [105]:
# Filter Sentinel 2 and cloud score plus images
start_date ='2022-12-01'
end_date ='2022-12-31'
AOI = AOI

S2 = sen2.filterBounds(AOI)\
.filterDate(start_date, end_date)\
.filterMetadata('CLOUDY_PIXEL_PERCENTAGE', 'less_than', 2)\
.linkCollection(csPlus, [QA_BAND])\
.map(lambda img: img.updateMask(img.select(QA_BAND).gt(threshold)))

'''The linkCollection function adds the 'cs_cdf' band from the cloud score plus
layer (defined above) to the Sentinel 2 bands.'''

print('Images found:', S2.size().getInfo()) # Gets the number of filtered images

Images found: 14


### Band information

In [60]:
# checking for band information
print("There are", S2.first().bandNames().size().getInfo(), "bands in the image\n")
print(f"Available bands {S2.first().bandNames().getInfo()}")

# Get projection information (CRS and nominal scale/resolution) from a single band
print("\nProjection information (from B2 band):", S2.first().select('B2').projection().getInfo())

# # Get image metadata properties
print("\nImage metadata properties:", S2.propertyNames().getInfo())

There are 27 bands in the image

Available bands ['B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B9', 'B11', 'B12', 'AOT', 'WVP', 'SCL', 'TCI_R', 'TCI_G', 'TCI_B', 'MSK_CLDPRB', 'MSK_SNWPRB', 'QA10', 'QA20', 'QA60', 'MSK_CLASSI_OPAQUE', 'MSK_CLASSI_CIRRUS', 'MSK_CLASSI_SNOW_ICE', 'cs_cdf']

Projection information (from B2 band): {'type': 'Projection', 'crs': 'EPSG:32630', 'transform': [10, 0, 499980, 0, -10, 800040]}

Image metadata properties: ['date_range', 'period', 'system:visualization_0_min', 'type_name', 'keywords', 'system:visualization_0_bands', 'thumb', 'description', 'source_tags', 'system:id', 'visualization_0_max', 'provider_url', 'title', 'sample', 'tags', 'system:visualization_0_max', 'product_tags', 'provider', 'visualization_0_min', 'system:version', 'system:visualization_0_name', 'visualization_0_name', 'visualization_0_bands']


In [ ]:
# Find the cloud percentage for each filtered image

# Get the number of images in the collection
num_images = S2.size().getInfo()

# Materialize the collection into a list on the server side
S2_list = S2.toList(num_images)

for i in range(num_images):
    # Get the image object from the list
    image = ee.Image(S2_list.get(i))

    # Extract the image ID and the cloud cover property
    image_id = image.get('system:index').getInfo()
    cloud_cover = image.get('CLOUDY_PIXEL_PERCENTAGE').getInfo()

    # Print the result, formatted to one decimal place
    print(f"Image ID: {image_id} | Cloud Cover: {cloud_cover:.1f}%")

    print("-------------------------------------------------")

In [73]:
# Combine all tiles into on image
composite = S2.median()

### Cloud Masking
Removes all pixels with clouds and cloud shadows

The cloud score-cumulative distribution function (cs_cdf) band of Cloud Score+  layer is added to S2 surface reflectance.This is a quality assessment (QA)
processor for medium-to-high resolution optical satellite imagery.
The Cloud Score+ S2_HARMONIZED dataset is being operationally produced
from the harmonized Sentinel-2 L1C collection, and Cloud Score+ outputs
can be used to identify relatively clear pixels and effectively
remove clouds and cloud shadows from L1C (Top-of-Atmosphere) or L2A
(Surface Reflectance) imagery. The Cloud Score+ S2_HARMONIZED dataset
includes two QA bands, cs and cs_cdf, that both grade the usability of
individual pixels with respect to surface visibility on a continuous
scale between 0 and 1, where 0 represents "not clear" (occluded),
while 1 represents "clear" (unoccluded) observations


#### Cloud Score Plus Approach

The Cloud Score+ is a quality assessment (QA) processor for medium-to-high resolution optical satellite imagery. The Cloud Score+ S2_HARMONIZED dataset is being operationally produced from the harmonized Sentinel-2 L1C collection, and Cloud Score+ outputs can be used to identify relatively clear pixels and effectively remove clouds and cloud shadows from L1C (Top-of-Atmosphere) or L2A (Surface Reflectance) imagery. The Cloud Score+ S2_HARMONIZED dataset includes two QA bands, cs and cs_cdf, that both grade the usability of individual pixels with respect to surface visibility on a continuous scale between 0 and 1, where 0 represents "not clear" (occluded), while 1 represents "clear" (unoccluded) observations.

In [79]:
# Masking using the Cloud Score+ function.
def mask_clouds_cs_plus(image):
    # use the 'cs' from cloud score+
    # 'cs' represent the clear score with 0 = cloudy and 1 = clear conditions
    qa = image.select('cs_cdf') # maybe use the cs_cdf layer?

    mask = qa.gte(0.60)  # can increase this threshold for higher output

    return image.updateMask(mask).divide(10000)

In [109]:
# Combine S2 and cloud score and apply mask
CSP_masked = (sen2.linkCollection(csPlus, ['cs_cdf']).map(mask_clouds_cs_plus).median())

In [94]:
# Display the filtered images
import geemap

Map = geemap.Map(basemap = geemap.basemaps.OpenStreetMap)
#Map.addLayer(sen2_clip, {'bands': ['B4', 'B3', 'B2'], 'min':0, 'max': 2000}, 'Sentinel 2') # The raw snetinel 2 collection
#Map.addLayer(composite, {'bands': ['B4', 'B3', 'B2'], 'min':0, 'max': 2000}, 'S2 composite')
Map.addLayer(s2_masked, {"bands": ["B4", "B3", "B2"], 'min':20, 'max':200}, 'cloud masked')
Map.centerObject(AOI, 8)

Map

Map(bottom=32020.0, center=[5.747174076651375, -2.4169921875000004], controls=(WidgetControl(options=['positio…

In [ ]:
# Get the band info for the s2_masked layer
#print(f"There are {s2_masked.size().getInfo()} images")
#print("There are", s2_masked.bandNames().size().getInfo(), "bands in the image\n")
#print(f"Available bands {s2_masked.bandNames().getInfo()}")
#print(f"There are {s2_masked.size().getInfo()} images")

#### Cloud Probability Approach

The S2 cloud probability is created with the sentinel2-cloud-detector library (using LightGBM). All bands are upsampled using bilinear interpolation to 10m resolution before the gradient boost base algorithm is applied. The resulting 0..1 floating point probability is scaled to 0..100 and stored as an UINT8. Areas missing any or all of the bands are masked out. Higher values are more likely to be clouds or highly reflective surfaces (e.g. roof tops or snow).

In [96]:
# step 1 - import and filter Sentinel-2 cloud probability dataset

S2_cloud = ee.ImageCollection('COPERNICUS/S2_CLOUD_PROBABILITY')
S2_cloud_prob = S2_cloud.filterBounds(AOI).filterDate(start_date, end_date)

#S2_cloud_prob.size().getInfo()


In [97]:
# Step 2 - Join the filtered s2cloudless collection to the SR collection by the 'system:index' property

filtered_sentinel2 = sen2.filterBounds(AOI).filterDate(start_date, end_date)

S2_joins = ee.Join.saveAll('clouds').apply(**{
    'primary': filtered_sentinel2, # Use the filtered S2 collection
    'secondary': S2_cloud_prob,
    'condition': ee.Filter.equals(**{
        'leftField': 'system:index',
        'rightField': 'system:index'
    })
})

# S2_joins.first().getInfo()  # Obtain information about one or more images

In [106]:
# Step 3 - Add the s2cloudless probability layer and derived cloud mask as bands to the S2 SR image

def add_cloud_bands(img_feature):
    # img_feature is already the Sentinel-2 image from the primary collection (filtered_sentinel2)
    s2_image = ee.Image(img_feature)

    # Get the s2cloudless image from the 'clouds' property of the feature.
    # The 'clouds' property contains an ee.List of joined cloud images.
    # We take the first (and typically only) matching cloud image.
    cld_img_list = ee.List(img_feature.get('clouds'))

    # If the list is empty (no cloud image joined), handle it gracefully
    # by using a default cloud probability image (e.g., all zeros or a constant)
    def get_cloud_prob_image(cloud_list):
        return ee.Algorithms.If(
            cloud_list.size().gt(0),
            ee.Image(cloud_list.get(0)).select('probability'),
            ee.Image(0).rename('probability').toUint8() # Default to 0 probability if no cloud image
        )

    # Apply the helper function to get the cloud probability image
    cld_prb_image = ee.Image(get_cloud_prob_image(cld_img_list))

    # Condition s2cloudless by the probability threshold value.
    # The 'threshold' variable is defined globally in the notebook (0.80)
    # Cloud probability is 0-100, so we multiply the threshold by 100.
    is_cloud = cld_prb_image.gt(threshold * 100).rename('clouds').toUint8()

    # Add the cloud probability layer and cloud mask as new bands to the original S2 image.
    return s2_image.addBands(ee.Image([cld_prb_image, is_cloud]))

cloudless_bands = S2_joins.map(add_cloud_bands)

# Convert cloudless_bands into an image collection and mosaic
CP_masked = ee.ImageCollection(cloudless_bands).mosaic()



In [107]:
# avilable bands for cloudless_band layer
print("There are", CP_masked.bandNames().size().getInfo(), "bands in the image\n")

print(f"Available bands {CP_masked.bandNames().getInfo()}")

There are 28 bands in the image

Available bands ['B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B9', 'B11', 'B12', 'AOT', 'WVP', 'SCL', 'TCI_R', 'TCI_G', 'TCI_B', 'MSK_CLDPRB', 'MSK_SNWPRB', 'QA10', 'QA20', 'QA60', 'MSK_CLASSI_OPAQUE', 'MSK_CLASSI_CIRRUS', 'MSK_CLASSI_SNOW_ICE', 'probability', 'clouds']


### Clip to study area

In [110]:
# Clip to study area
CSP_masked = CSP_masked.clip(AOI) # Result of the cloud score plus mask
CP_masked = CP_masked.clip(AOI)  # Result of the cloud probability mask

### Resample bands
The 6 bands (5, 6, 7, 8A, 11, 12) with 20m spatial rsolution are resampled to correspond with other 10m bands (2, 3, 4, and 8B) using the 'reproject' in Google Earth Engine

In [111]:
# Select the 20m bands
bands_20m = CSP_masked.select('B5', 'B6', 'B7', 'B8A', 'B11', 'B12','cs_cdf')

# Use the projection of a 10m band (e.g., 'B2') as reference to resample others
projection_10m = CSP_masked.select('B2').projection()

# Create a target projection object with 10m scale
target_projection = projection_10m.atScale(10)

# Reproject the 20m bands to 10m resolution using the target projection object
resampled_bands = bands_20m.reproject(target_projection)

print("The selectd 20m bands have been successully reprojected to 10m resolution as shown below:\n")
#resampled_bands.getInfo()

The selectd 20m bands have been successully reprojected to 10m resolution as shown below:



**Combine resampled bands to the other bands**

In [112]:
# Select the 10m bands
bands_10m = CSP_masked.select('B2', 'B3', 'B4', 'B8')

# Combine the original 10m bands with the resampled 20m bands
S2_resampled = bands_10m.addBands(resampled_bands)

print("Original 10m bands combined with resampled 20m bands. The final images now contains all bands at 10m resolution.\n")
#S2_resampled.getInfo()

Original 10m bands combined with resampled 20m bands. The final images now contains all bands at 10m resolution.



**CRS**
Reproject the entire image to EPSG:3857 (Web Mercator) projected coordinate system


In [113]:
# Define a projected coordinate system (e.g., Web Mercator) with a 10m scale
projected_crs = 'EPSG:3857' # Web Mercator, suitable for global display
output_scale = 10 # 10 meters

# Reproject the entire combined image to the desired projected CRS and scale
S2_reprojected = S2_resampled.reproject(
    crs = projected_crs,
    scale = output_scale
)

print(f"The combined image has been reprojected to {projected_crs} with a {output_scale}m resolution.")
print("Now, all bands should have consistent crs_transform values directly representing meters per pixel:")
#S2_reprojected.getInfo()

The combined image has been reprojected to EPSG:3857 with a 10m resolution.
Now, all bands should have consistent crs_transform values directly representing meters per pixel:


In [114]:
# Band information for the reprojectd layer
bands = S2_reprojected.bandNames().getInfo()

print("Spatial resolution for each band in S2 reprojectd layer:")
for band_name in bands:
    # Get the nominal scale (spatial resolution) of the band's projection
    scale = S2_reprojected.select(band_name).projection().nominalScale().getInfo()
    print(f"Band {band_name}: {scale} meters")

print(S2_reprojected.bandNames().getInfo()) # Final bands
print(S2_reprojected.projection().getInfo()) # Web Mercator projection

Spatial resolution for each band in S2 reprojectd layer:
Band B2: 10 meters
Band B3: 10 meters
Band B4: 10 meters
Band B8: 10 meters
Band B5: 10 meters
Band B6: 10 meters
Band B7: 10 meters
Band B8A: 10 meters
Band B11: 10 meters
Band B12: 10 meters
Band cs_cdf: 10 meters
['B2', 'B3', 'B4', 'B8', 'B5', 'B6', 'B7', 'B8A', 'B11', 'B12', 'cs_cdf']
{'type': 'Projection', 'crs': 'EPSG:3857', 'transform': [10, 0, 0, 0, -10, 0]}


### Visualise filtered images

In [130]:
# Define visualisation parameters
vis_params = {'bands': ['B4', 'B3', 'B2'], 'min': 0.02, 'max': 0.2}

In [134]:
import geemap

# Initialize the map
Map = geemap.Map(basemap = geemap.basemaps.OpenStreetMap) # can change the basemap to "SATELLITE"

# Add the final image to the interactive map

Map.addLayer(S2_reprojected, vis_params, 'SCP approach')
Map.addLayer(AOI, {'min':0, 'max': 2000, 'color':"red"}, 'AOI')

#Map.addLayer(composite2, vis_params, '2nd approach')

# Set the centre of the map to the study area
Map.centerObject(AOI, 8)

# Display the map
Map

Map(center=[5.741311800540024, -2.4134022722293973], controls=(WidgetControl(options=['position', 'transparent…

## Part 2 - Classification

### Install and import libraries for classification

In [ ]:
# Install packages
!pip install geopandas # Vector model
!pip install rasterio  # Raster model
!pip install scikit-learn # Machine learning library (SVM, RF and KNN)
#!pip install torch torchvision torchaudio # Deep learning model (YOLO & U-Net)
#!pip install ultralytics # YOLO v8 model
#!pip install segmentation_models_pytorch # Segmentation model for U-Net
#!pip install opencv-python # Image processing with deep learning

In [137]:
# Import necessary libraries
import geopandas as gpd
import rasterio
import pandas as pd

from rasterio.mask import mask
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

#import torch
#import torch.nn as nn
#import torch.optim as optim
#from torch.utils.data import Dataset, DataLoader
#from ultralytics import YOLO
#import segmentation_models_pytorch as smp
#import cv2
import numpy as np

### Load  and prepare training data - polygon

In [139]:
# Load training data from GEE
t_data = ee.FeatureCollection('projects/ee-abutunghem/assets/PhD/Classification/Samples/TrainingSamples_All_unmerged')

print('The are:', t_data.size().getInfo(), 'feature classes')
gpd.GeoDataFrame.from_features(t_data.limit(5).getInfo()['features'])

The are: 5300 feature classes


geometry  BLUE Classcode  \
0  POLYGON ((-2.90132 6.65636, -2.90119 6.65636, ...     0         4   
1  POLYGON ((-2.94529 6.65588, -2.94517 6.65589, ...     0         4   
2  POLYGON ((-2.90001 6.65568, -2.9 6.65577, -2.9...     0         4   
3  POLYGON ((-2.94061 6.65461, -2.94054 6.65461, ...     0         4   
4  POLYGON ((-2.94128 6.65372, -2.94124 6.65379, ...     0         4   

         Classname  Classvalue  Count  GREEN  RED  
0  Developed Areas           4    114     56  168  
1  Developed Areas           4    100     56  168  
2  Developed Areas           4     66     56  168  
3  Developed Areas           4     57     56  168  
4  Developed Areas           4     53     56  168

To convert the training data (polygons) into a format compatible with scikit-learn for SVM, RF, and KNN classification, we sampled the pixel values from Sentinel-2 image at the locations defined by these polygons, from which the sampled data were structured into features (X) and labels (y) that scikit-learn models can train on. The steps taken to achieve this are as follows\n:
a). Define classification bands
b). Extract training pixels frim the image
c). Convert sampled data to Pandas dataframe
d). Prepare features (x) and labels (y)
e). Split data into traning and testing

In [140]:
# Step 1- Define classification bands from the filtered sentinel 2 image cliped to Western Ghana
classification_bands = S2_reprojected.select(
    ['B2', 'B3', 'B4', 'B5','B6', 'B7',
    'B8', 'B8A', 'B11', 'B12'])
#print(classification_bands.bandNames().getInfo())

Use the sampleRegions method from Google Earth Engine to extract pixel values for the selected bands within the training_data polygons. This operation will generate a new ee.FeatureCollection where each feature represents a sampled pixel, containing its spectral values and the corresponding class label from the polygon it originated from

In [144]:
# Step 2 - Extract Training Pixels from the image based on the training polygons

label = 'Classname' # the property name in t_data that contains the class labels

sampled_data = classification_bands.sampleRegions(**{
    'collection': t_data,
    'properties': [label],
    'scale': 10 # Set scale to 10 meters, consistent with the resampled bands
})

# This returns the total number of individual 10x10 meter pixels sampled from across all 5300 training polygons

# To filter the sampled_data for each class using the filter() method.
developed_pixels = sampled_data.filter(ee.Filter.eq(label, "Developed Areas"))
Cocoa = sampled_data.filter(ee.Filter.eq(label, "Cocoa plots"))
crop = sampled_data.filter(ee.Filter.eq(label, "Crop land"))
forest = sampled_data.filter(ee.Filter.eq(label, "Forest"))
mining = sampled_data.filter(ee.Filter.eq(label, "Mining"))
water = sampled_data.filter(ee.Filter.eq(label, "Water"))


# print('Size of sampled_data:', sampled_data.size().getInfo()) # Commented out to prevent memory error
#print('Sampled data for the first feature:\n', sampled_data.first().getInfo())
'''
print('\nNumber of pixels for each class:')
print('developed_pixels:',developed_pixels.size().getInfo())
print('cocoa:', Cocoa.size().getInfo())
print('crop:', crop.size().getInfo())
print('forest:', forest.size().getInfo())
print('minning:', mining.size().getInfo())
print('water:', water.size().getInfo())
'''

"\nprint('\nNumber of pixels for each class:')\nprint('developed_pixels:',developed_pixels.size().getInfo())\nprint('cocoa:', Cocoa.size().getInfo())\nprint('crop:', crop.size().getInfo())\nprint('forest:', forest.size().getInfo())\nprint('minning:', mining.size().getInfo())\nprint('water:', water.size().getInfo())\n"

###Step 3- Convert Sampled Data to Pandas DataFrame
Convert the `sampled_data` (ee.FeatureCollection) into a Pandas DataFrame, which is required for scikit-learn models. This will involve fetching the data from Earth Engine and structuring it appropriately.


In [151]:
# Get the list of all band names used for classification and the label column
all_properties = classification_bands.bandNames().getInfo() + [label]

# To avoid the 'User memory limit exceeded' error, limit the number of sampled features
# before attempting to retrieve them to the client. This creates a subset of the data.
# Adjust the limit based on available memory and the representativeness needed for your training.
# Ideally, sampling should be limited in the ee.Image.sampleRegions call itself for efficiency.
limited_sampled_data = sampled_data.limit(1000) # Further reduced limit to 1,000 features to avoid memory issues

# Get the client-side representation of the limited FeatureCollection
# This is a more direct way to transfer sampled data for a manageable number of features.
feature_collection_info = limited_sampled_data.getInfo()

# Extract the list of features (dictionaries) from the info object
features = feature_collection_info['features']

# Create a list of dictionaries, where each dictionary represents the properties of one feature
# These properties include the band values and the 'Classname' label.
data_for_df = [feature['properties'] for feature in features]

# Create the Pandas DataFrame from the list of dictionaries
df = pd.DataFrame(data_for_df)

# Display the first few rows of the created DataFrame and its information
'''print("First 5 rows of the DataFrame:")
print(df.head())
print("\nDataFrame Information:")
df.info()
print(f"\nDataFrame successfully created with {len(df)} rows.")'''

EEException: User memory limit exceeded.

###Step 4- Prepare Features (X) and Labels (y)
Extract the spectral band values from the DataFrame as features (X) and the 'Classname' values as labels (y), converting class names to numerical representations if necessary.


In [ ]:
# 1. Define the feature columns (spectral bands) by excluding the 'Classname' column
X = df.drop('Classname', axis=1)

# 2. Extract the 'Classname' column as labels
y_categorical = df['Classname']

# 3. Convert the categorical labels in y into numerical representations
y, class_names = pd.factorize(y_categorical) # pd.factorize returns an array of numerical labels and a unique list of categories

# 4. Print the first five rows of X and y to inspect the prepared features and labels
#print("First 5 rows of Features (X):")
#print(X.head())

#print("\nFirst 5 rows of Labels (y) (numerical):")
#print(y[:5])

print("\nMapping of numerical labels to original class names:")
for i, name in enumerate(class_names):
    print(f"{i}: {name}")


First 5 rows of Features (X):
       B2      B3      B4      B5      B6      B7      B8     B8A     B11  \
0   698.0   942.0  1344.0  1327.0  2140.0  2480.0  2568.0  2685.0  2590.0   
1   814.0  1092.0  1310.0  1451.0  2052.0  2330.0  2156.0  2530.0  2713.0   
2  1134.0  1244.0  1492.0  1451.0  2052.0  2330.0  2114.0  2530.0  2713.0   
3   576.0   693.0   878.0  1032.5  1827.0  2136.5  1546.0  2229.5  1924.5   
4   618.5   772.5   940.0  1017.5  1744.0  2004.0  1666.5  2115.0  1869.5   

      B12  
0  1989.0  
1  2269.0  
2  2269.0  
3  1262.0  
4  1375.0  

First 5 rows of Labels (y) (numerical):
[0 0 0 0 0]

Mapping of numerical labels to original class names:
0: Developed Areas
1: Mining
2: Cocoa plots
3: Forest
4: Crop land
5: Water


###Step 5- Split Data into Training and Testing Sets
Divide the prepared features (X) and labels (y) into training and testing subsets using `sklearn.model_selection.train_test_split` to evaluate model performance.


In [ ]:
# Split the features X and labels y into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# x_train (training feature), x_test(test), y_train(training labels), y_test(test labels)
# test_size (0.2 = 20% test and 80% training), random_state()

# size of the training and test data
print(f"There are {X_train.size} pixels in the training set")
print(f"There are {X_test.size} pixels in the test set\n")

# Print the shapes of the resulting sets to verify the split proportions
print(f"training features: {X_train.shape}") # number of pixels, number of bands
print(f"training labels: {y_train.shape}")
print(f"test features: {X_test.shape}")
#print('training features:', X_test)


There are 165790 pixels in the training set
There are 41450 pixels in the test set

training features: (16579, 10)
training labels: (16579,)
test features: (4145, 10)


## Machine Learning

In [ ]:
# Create a dictionary to map string class names (derived from pd.factorize(y_categorical) to numerical IDs
numerical_labels = ee.Dictionary.fromLists(ee.List(class_names.tolist()), ee.List.sequence(0, len(class_names) - 1))

# Map over the sampled_data FeatureCollection to add a new numerical property 'class_id'
sampled_data_numeric = sampled_data.map(lambda f: f.set('class_id', numerical_labels.get(f.get('Classname'))))

print("Sampled data updated with numerical 'class_id' property for GEE training.")
#print('Sampled data with numeric labels for the first feature:\n', sampled_data_numeric.first().getInfo())

Sampled data updated with numerical 'class_id' property for GEE training.


### SVM Classification
Initialize and train a Support Vector Machine (SVM) classifier using `X_train` and `y_train`. Then, apply the trained SVM model to classify the entire `classification_bands` image, creating an `ee.Image` of predicted classes.


In [ ]:
# Import support vector classifier (SVC)
from sklearn.svm import SVC

# Set parameter for the SVM classifier
svm_model = SVC(kernel='linear', random_state=42)

# Train the SVM classifier with the training data
svm_model.fit(X_train, y_train)

print("SVM model trained successfully.")

SVM model trained successfully.


Convert the trained SVM model into an Earth Engine compatible classifier and then use it to classify the `classification_bands` image, which is an Earth Engine object.



In [ ]:
# Define the input properties (i.e classification_bands) for the GEE classifier

SVM_properties = classification_bands.bandNames()

# Initialize an GEE LIBSVM classifier (replaces the deprecated ee.Classifier.svm)
ee_svm_classifier_params = {
    'kernelType': 'LINEAR', # Corresponds to kernel='linear' in scikit-learn
    'cost': 10             # A common value for C; adjust as needed
    }


ee_svm_classifier = ee.Classifier.libsvm(**ee_svm_classifier_params)

# Train the LIBSVM classifier using the sampled_data_numeric (ee.FeatureCollection).
trained_ee_svm_classifier = ee_svm_classifier.train(
    features = sampled_data_numeric,
    classProperty ='class_id', # Use the new numerical 'class_id' property
    inputProperties = SVM_properties
)

# Apply the trained LIBSVM classifier to the entire classification_bands image.
svm_classified_image = classification_bands.classify(trained_ee_svm_classifier) # The .classify() method takes the image to classify and the trained classifier.

print("Earth Engine SVM classifier trained using numerical 'class_id' and applied to the image.")
#print(svm_classified_image.getInfo()) # metadata of the classified image
#print(svm_classified_image.bandNames().size().getInfo()) # number of bands

Earth Engine SVM classifier trained using numerical 'class_id' and applied to the image.


### RF Classification
Initialise and train a Random Forest classifier using `X_train` and `y_train`. Subsequently, use the trained Random Forest model to classify the `classification_bands` image, generating an `ee.Image` of predicted classes.


In [ ]:
# Import the RF classifier
from sklearn.ensemble import RandomForestClassifier

# Initialize the Random Forest classifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the Random Forest classifier with the training data
rf_model.fit(X_train, y_train)

print("Random Forest model trained successfully.")

Random Forest model trained successfully.


Use the trained Random Forest model to initialise GEE Random Forest classifier with similar parameters, train it using the `sampled_data` (ee.FeatureCollection), and then apply this trained classifier to the `classification_bands` image.



In [ ]:
# Define the input properties for the Earth Engine classifier (the band names)
RF_properties = classification_bands.bandNames()

# Initialize an Earth Engine Random Forest classifier with parameters similar to scikit-learn's
# The number of trees and seed are often chosen to match the scikit-learn model for consistency
ee_rf_classifier = ee.Classifier.smileRandomForest(**{
    'numberOfTrees': 100,
    'seed': 42
})

# Train the Earth Engine Random Forest classifier using the sampled_data_numeric (ee.FeatureCollection).
trained_ee_rf_classifier = ee_rf_classifier.train(
    features = sampled_data_numeric,
    classProperty = 'class_id', # Use the new numerical 'class_id' property
    inputProperties = RF_properties
)

# Apply the trained Earth Engine Random Forest classifier to the entire classification_bands image.
rf_classified_image = classification_bands.classify(trained_ee_rf_classifier)

print("Earth Engine RF classifier trained using numerical 'class_id' and applied to the image.")
# print(rf_classified_image.getInfo()) # metadata of the classified image

Earth Engine RF classifier trained using numerical 'class_id' and applied to the image.


### KNN Classification:
Initialize and train a K-Nearest Neighbors (KNN) classifier using `X_train` and `y_train`. Finally, apply the trained KNN model to classify the `classification_bands` image, resulting in an `ee.Image` of predicted classes.


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Initialize the KNN classifier with n_neighbors=5
knn_model = KNeighborsClassifier(n_neighbors=5)

# Train the KNN classifier with the training data
knn_model.fit(X_train, y_train)

print("KNN model trained successfully.")

KNN model trained successfully.


In [ ]:
# Define the input properties for the Earth Engine classifier (the band names)
KNN_properties = classification_bands.bandNames()

# Initialize an Earth Engine Minimum Distance classifier
ee_knn_classifier = ee.Classifier.smileKNN()

# Train the Earth Engine Minimum Distance classifier using the sampled_data_numeric (ee.FeatureCollection).
trained_ee_knn_classifier = ee_knn_classifier.train(
    features = sampled_data_numeric,  #the ee.FeatureCollection containing the sampled pixels with their labels
    classProperty = 'class_id',       # Use the new numerical 'class_id' property
    inputProperties = KNN_properties  #names of the properties in 'features' that are used as training features.
)

# Apply the trained Earth Engine Minimum Distance classifier to the entire classification_bands image.
knn_classified_image = classification_bands.classify(trained_ee_knn_classifier)

print("Earth Engine KNN classifier trained using numerical 'class_id' and applied to the image.")
# print(knn_classified_image.getInfo()) # metadata of the classified image

Earth Engine KNN classifier trained using numerical 'class_id' and applied to the image.


## Accuracy Assessment
Compares the performance of the 3 models using confusion matrix including OA, PA, UA, recall and precision

In [ ]:
# Import libraries
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

### SVM Accuracy

In [ ]:
# Define prediction value
svm_predictions = svm_model.predict(X_test)

# Confusion matrix
svm_confusion_matrix = confusion_matrix(y_test, svm_predictions)

# Overall Accuracy, weighted precision, and weighted recall
SVM_OA = np.diag(svm_confusion_matrix).sum() / svm_confusion_matrix.sum()
SVM_Precision = precision_score(y_test, svm_predictions, average='weighted')
SVM_recall = recall_score(y_test, svm_predictions, average='weighted')
SVM_F1 = f1_score(y_test, svm_predictions, average='weighted')

# Producer's Accuracy (correctly classified samples of each class) / (total actual samples of each class)
# np.diag - correctly classified samples for each class
# np.sum(svm_confusion_matrix, axis=1) gives the total actual samples for each class (row sums)
SVM_PA = np.diag(svm_confusion_matrix) / np.sum(svm_confusion_matrix, axis=1)

# User's Accuracy UA = (correctly classified samples of class i) / (total predicted samples of class i)
# np.sum(svm_confusion_matrix, axis=0) gives the total predicted samples for each class (column sums)
SVM_UA = np.diag(svm_confusion_matrix) / np.sum(svm_confusion_matrix, axis=0)

print(f"Overall Accuracy: {SVM_OA:.6f}")
print(f"Overall Precision: {SVM_Precision:.6f}")
print(f"Overall Recall: {SVM_recall:.6f}")
print(f"Overall F1-score: {SVM_F1:.6f}")

print("\nPer-Class Producer's Accuracy:")
for i, pa in enumerate(SVM_PA):
    print(f"  Class {class_names[i]}: {pa:.2f}")

print("\nPer-Class User's Accuracy:")
for i, ua in enumerate(SVM_UA):
    print(f"  Class {class_names[i]}: {ua:.2f}")

print("\nConfusion Matrix:")
print(svm_confusion_matrix)

Overall Accuracy: 0.929312
Overall Precision: 0.928726
Overall Recall: 0.929312
Overall F1-score: 0.927987

Per-Class Producer's Accuracy:
  Class Developed Areas: 0.97
  Class Mining: 0.64
  Class Cocoa plots: 0.93
  Class Forest: 0.94
  Class Crop land: 0.95
  Class Water: 0.66

Per-Class User's Accuracy:
  Class Developed Areas: 0.97
  Class Mining: 0.86
  Class Cocoa plots: 0.92
  Class Forest: 0.90
  Class Crop land: 0.93
  Class Water: 0.89

Confusion Matrix:
[[ 670    3    0    4   16    1]
 [   8   76    0    0   29    6]
 [   0    0  745   14   44    0]
 [   0    0   11  459   20    0]
 [  13    3   49   32 1828    2]
 [   1    6    5    2   24   74]]


**Note**
The average parameter determines how the precision scores for each class are combined into a single, overall precision score:

None: If you set average=None, the precision_score function will return a precision score for each individual class. This is useful if you want to see the performance for each class independently.

'micro': Calculates precision globally by counting the total true positives, false negatives, and false positives. It's equivalent to overall accuracy when classes are perfectly balanced. This is often used when you want to give equal importance to each sample.

'macro': Calculates precision for each label, and then averages them without considering the proportion of samples for each label. This gives equal weight to each class, regardless of how many samples belong to that class. If you have an imbalanced dataset, a small class can heavily influence the macro average.

'weighted': This is the one we used. It calculates precision for each label and then averages them, but it weighs each class's precision score by the number of true instances for that class.

Why 'weighted'? In our land classification scenario, some land cover types (like 'Crop land') might have many more pixels (instances) than others (like 'Mining'). Using average='weighted' ensures that classes with more samples contribute more to the overall average precision, making the metric more representative of the model's performance on the dataset as a whole, especially if the dataset is imbalanced. It's a good choice when you want the metric to reflect the average precision where the contribution of each class is proportional to its presence in the dataset.
So, by using average='weighted', we get a single precision score that takes into account the varying number of pixels in each land cover class, providing a more balanced view of the model's overall precision across the entire test set.

### RF Accuracy

In [ ]:
# Define RF predictions
RF_predictions = rf_model.predict(X_test)

# Confusion matrix
RF_confusion_matrix = confusion_matrix(y_test, RF_predictions)

# Overall Accuracy, weighted precision, and weighted recall
RF_OA = np.diag(RF_confusion_matrix).sum() / RF_confusion_matrix.sum()
RF_Precision = precision_score(y_test, RF_predictions, average='weighted')
RF_recall = recall_score(y_test, RF_predictions, average='weighted')
RF_F1 = f1_score(y_test, RF_predictions, average='weighted')

# Producer's Accuracy (correctly classified samples of each class) / (total actual samples of each class)
# np.diag - correctly classified samples for each class
# np.sum(svm_confusion_matrix, axis=1) gives the total actual samples for each class (row sums)
RF_PA = np.diag(RF_confusion_matrix) / np.sum(RF_confusion_matrix, axis=1)

# User's Accuracy UA = (correctly classified samples of class i) / (total predicted samples of class i)
# np.sum(svm_confusion_matrix, axis=0) gives the total predicted samples for each class (column sums)
RF_UA = np.diag(RF_confusion_matrix) / np.sum(RF_confusion_matrix, axis=0)

print(f"Overall Accuracy: {RF_OA:.2f}")
print(f"Overall Precision: {RF_Precision:.2f}")
print(f"Overall Recall: {RF_recall:.2f}")
print(f"Overall F1-score: {RF_F1:.2f}")

print("\nPer-Class Producer's Accuracy:")
for i, pa in enumerate(RF_PA):
    print(f"  Class {class_names[i]}: {pa:.2f}")

print("\nPer-Class User's Accuracy:")
for i, ua in enumerate(RF_UA):
    print(f"  Class {class_names[i]}: {ua:.2f}")

print("\nConfusion Matrix:")
print(RF_confusion_matrix)

Overall Accuracy: 0.96
Overall Precision: 0.96
Overall Recall: 0.96
Overall F1-score: 0.96

Per-Class Producer's Accuracy:
  Class Developed Areas: 0.97
  Class Mining: 0.72
  Class Cocoa plots: 0.97
  Class Forest: 0.97
  Class Crop land: 0.98
  Class Water: 0.76

Per-Class User's Accuracy:
  Class Developed Areas: 0.96
  Class Mining: 0.96
  Class Cocoa plots: 0.96
  Class Forest: 0.94
  Class Crop land: 0.96
  Class Water: 0.96

Confusion Matrix:
[[ 671    3    0    2   18    0]
 [  10   86    0    0   21    2]
 [   0    0  775   12   16    0]
 [   0    0    8  475    6    1]
 [  11    0   18   11 1886    1]
 [   7    1    5    4   10   85]]


### KNN Accuracy

In [ ]:
# Define RF predictions
KNN_predictions = knn_model.predict(X_test)

# Confusion matrix
KNN_confusion_matrix = confusion_matrix(y_test, KNN_predictions)

# Overall Accuracy, precision, and recall
KNN_OA = np.diag(KNN_confusion_matrix).sum() / KNN_confusion_matrix.sum()
KNN_Precision = precision_score(y_test, KNN_predictions, average='weighted')
KNN_recall = recall_score(y_test, KNN_predictions, average='weighted')
KNN_F1 = f1_score(y_test, KNN_predictions, average='weighted')

# Producer's Accuracy (correctly classified samples of each class) / (total actual samples of each class)
# np.diag - correctly classified samples for each class
# np.sum(svm_confusion_matrix, axis=1) gives the total actual samples for each class (row sums)
KNN_PA = np.diag(KNN_confusion_matrix) / np.sum(KNN_confusion_matrix, axis=1)

# User's Accuracy UA = (correctly classified samples of class i) / (total predicted samples of class i)
# np.sum(svm_confusion_matrix, axis=0) gives the total predicted samples for each class (column sums)
KNN_UA = np.diag(KNN_confusion_matrix) / np.sum(KNN_confusion_matrix, axis=0)

print(f"Overall Accuracy: {KNN_OA:.2f}")
print(f"Overall Precision: {KNN_Precision:.2f}")
print(f"Overall Recall: {KNN_recall:.2f}")
print(f"Overall F1-score: {KNN_F1:.2f}")

print("\nPer-Class Producer's Accuracy:")
for i, pa in enumerate(KNN_PA):
    print(f"  Class {class_names[i]}: {pa:.2f}")

print("\nPer-Class User's Accuracy:")
for i, ua in enumerate(KNN_UA):
    print(f"  Class {class_names[i]}: {ua:.2f}")

print("\nConfusion Matrix:")
print(KNN_confusion_matrix)

Overall Accuracy: 0.93
Overall Precision: 0.93
Overall Recall: 0.93
Overall F1-score: 0.92

Per-Class Producer's Accuracy:
  Class Developed Areas: 0.95
  Class Mining: 0.61
  Class Cocoa plots: 0.95
  Class Forest: 0.89
  Class Crop land: 0.96
  Class Water: 0.50

Per-Class User's Accuracy:
  Class Developed Areas: 0.97
  Class Mining: 0.90
  Class Cocoa plots: 0.88
  Class Forest: 0.91
  Class Crop land: 0.93
  Class Water: 0.92

Confusion Matrix:
[[ 659    6    2    0   27    0]
 [  12   73    0    0   31    3]
 [   0    0  761   16   26    0]
 [   0    0   32  435   22    1]
 [   5    0   56   12 1853    1]
 [   4    2   10   16   24   56]]


## Visualise Classified images
Display the classified images from SVM, Random Forest, and KNN on an interactive map using geemap with appropriate visualisation parameters and legends to distinguish between different land cover classes.


In [ ]:
import geemap

# Define a function to clean classified images by selecting the classification band,casting to Uint8, and renaming it to 'classification'.
def clean_classified_image(classified_img):
    # Select the first band (which is the classification result) and ensure it's numerical and named generically.
    return classified_img.select([0]).toUint8().rename('classification')

# Apply the cleaning function to each classified image to prepare for visualization
cleaned_svm_classified_image = clean_classified_image(svm_classified_image)
cleaned_rf_classified_image = clean_classified_image(rf_classified_image)
cleaned_knn_classified_image = clean_classified_image(knn_classified_image)

# Define a visualization scale (e.g., 100m) to prevent timeouts for large AOIs
display_scale = 500 # metre - the original classification was at 10m, but for display, a coarser scale is often necessary.
display_crs = 'EPSG:3857' # Web Mercator

# Reproject the cleaned images to the display scale and CRS for visualization
displayed_svm_classified_image = cleaned_svm_classified_image.reproject(crs=display_crs, scale=display_scale)
displayed_rf_classified_image = cleaned_rf_classified_image.reproject(crs=display_crs, scale=display_scale)
displayed_knn_classified_image = cleaned_knn_classified_image.reproject(crs=display_crs, scale=display_scale)

# 1. Define visualization parameters for the classified images
palette = [
    '#FF0000',  # Developed Areas (Red)
    '#FFA500',  # Mining (Orange)
    '#FFFF00',  # Cocoa plots (Yellow)
    '#228B22',  # Forest (Forest Green)
    '#CCCCCC',  # Crop land (Gray)
    '#0000FF'   # Water (Blue)
]

vis_params_classified = {
    'min': 0, # Minimum class value (from pd.factorize output)
    'max': len(class_names) - 1, # Maximum class value
    'palette': palette
}

# 2. Initialize a geemap.Map() object
Map = geemap.Map()

# Add the original AOI for context
Map.addLayer(AOI, {'min':0, 'max': 2000, 'color':"red"}, 'Study Area Boundary')

# 3. Add the reprojected classified images to the map
Map.addLayer(displayed_svm_classified_image, vis_params_classified, 'SVM Classification (500m)')
Map.addLayer(displayed_rf_classified_image, vis_params_classified, 'Random Forest Classification (500m)')
Map.addLayer(displayed_knn_classified_image, vis_params_classified, 'Minimum Distance Classification (500m)')

# 6. Center the map on the AOI
Map.centerObject(AOI, 8)

# 8. Add a legend to the map by providing keys and colors as lists
Map.add_legend(keys=class_names.tolist(), colors=palette, title='Land Cover Classes')

# 9. Display the interactive map
print("Displaying the interactive map with classified results.")
Map

EEException: Computation timed out.

## Summary:

You've successfully computed and displayed the Overall Accuracy for the SVM model: 0.93.

Let's also look at the Overall Accuracies for the Random Forest and KNN models for comparison:

You've successfully computed and displayed the Overall Accuracies for all three models:

SVM Overall Accuracy: 0.93
Random Forest Overall Accuracy: 0.96
KNN Overall Accuracy: 0.96
It appears that both Random Forest and KNN models achieved a slightly higher overall accuracy compared to SVM for this classification task.

All right, all the accuracy metrics have been computed. Let's summarize the classification process and compare the performance of the three machine learning models:

Summary of the Classification Process:

Data Preparation: Earth Engine FeatureCollection data was converted into a Pandas DataFrame, overcoming Earth Engine's 5000-element getInfo() limit by aggregating properties individually. Spectral band values were extracted as features (X), and 'Classname' values as labels (y). Categorical class names were converted into numerical representations (0-5) using pd.factorize(). The data was then split into training (80%) and testing (20%) sets.
Model Training and Classification: Three classifiers—Support Vector Machine (SVM), Random Forest (RF), and K-Nearest Neighbors (KNN)—were trained using scikit-learn for local preparation and their respective Earth Engine equivalents for image classification. This involved adapting parameters and handling API differences, deprecations, and data type requirements between scikit-learn and Earth Engine (e.g., using ee.Classifier.libsvm() for SVM, ee.Classifier.smileRandomForest() for RF, and ee.Classifier.smileKNN() for KNN).
Visualization: The classified images from each model were displayed on an interactive geemap map, with appropriate visualization parameters and legends.
Comparison of Model Results and Performance:

We have calculated the following overall accuracies:

SVM Overall Accuracy: 0.93
Random Forest Overall Accuracy: 0.96
KNN Overall Accuracy: 0.96
Both Random Forest and KNN models achieved a slightly higher overall accuracy (96%) compared to the SVM model (93%). Let's delve into other performance metrics:

SVM Performance:

Overall Precision: 0.93
Overall Recall: 0.93
Per-Class Producer's Accuracy (PA): Ranged from 0.64 (Mining) to 0.97 (Developed Areas).
Per-Class User's Accuracy (UA): Ranged from 0.86 (Mining) to 0.97 (Developed Areas).
Random Forest Performance:

Overall Precision: 0.96
Overall Recall: 0.96
Per-Class Producer's Accuracy (PA): Ranged from 0.72 (Mining) to 0.98 (Crop land).
Per-Class User's Accuracy (UA): Ranged from 0.94 (Forest) to 0.96 (Mining, Cocoa plots, Crop land, Water).
KNN Performance:

Overall Precision: 0.96
Overall Recall: 0.96
Per-Class Producer's Accuracy (PA): Ranged from 0.72 (Mining) to 0.98 (Crop land).
Per-Class User's Accuracy (UA): Ranged from 0.94 (Forest) to 0.96 (Mining, Cocoa plots, Crop land, Water).
Discussion:

Overall Accuracy: Random Forest and KNN models demonstrated superior overall accuracy (0.96) compared to SVM (0.93). This suggests that for this specific dataset and feature set, tree-based ensemble methods and instance-based learning might capture the underlying patterns more effectively.
Per-Class Accuracy: While RF and KNN generally perform better, the 'Mining' class shows the lowest Producer's Accuracy across all models (0.64 for SVM, 0.72 for RF and KNN). This indicates that the models struggle to correctly identify actual 'Mining' areas, potentially misclassifying them as other land cover types. The 'Water' class also shows comparatively lower PA for SVM (0.66) and slightly better for RF/KNN (0.76).
Precision and Recall: The higher overall precision and recall for RF and KNN reinforce their better performance, indicating a better balance between correctly identifying positive cases and not misclassifying negative cases.
Key Findings Summary:

The Random Forest and KNN models are generally more robust for this land cover classification task, exhibiting higher overall accuracies and better per-class performance, especially for the more challenging classes like 'Mining' and 'Water'.
The difference in performance suggests that the data might benefit from non-linear decision boundaries or a voting ensemble approach, which RF and KNN are better suited for than a linear SVM.

# Export

In [ ]:
# Check for the current working directory
!cd "/content/drive/MyDrive/Colab Notebooks/PhD Data"

In [ ]:
# Content of the a directory
!ls "/content/drive/MyDrive/Colab Notebooks/PhD Data/"

 Codes	 Data  'Deep learning'	'Machine Learning'  'Sample Data'  'Sentinel 2'


In [ ]:
!ls "/content/drive/MyDrive/Colab Notebooks/PhD Data/Sentinel 2"

## Export accuracy result

In [ ]:
# Export confusion matrix with producer and user accuracy to csv

# Define the base path for saving files in Google Drive
output_folder = "/content/drive/MyDrive/Colab Notebooks/PhD Data/Sentinel 2"

# --- SVM Confusion Matrix with Accuracies ---
svm_cm_df = pd.DataFrame(svm_confusion_matrix, index=class_names, columns=class_names)

# Add Producer's Accuracy as a new column
svm_cm_df['Producer_Accuracy'] = pd.Series(SVM_PA, index=class_names)

# Add User's Accuracy as a new row, filling non-applicable columns with NaN
user_accuracy_row_svm = pd.Series(SVM_UA, index=class_names, name='User_Accuracy')
user_accuracy_row_extended_svm = user_accuracy_row_svm.reindex(svm_cm_df.columns, fill_value=np.nan)
svm_cm_df = pd.concat([svm_cm_df, user_accuracy_row_extended_svm.to_frame().T])

# Add Overall Accuracy as a new row, filling non-applicable columns with NaN
overall_accuracy_data_svm = [SVM_OA] + [np.nan] * (len(svm_cm_df.columns) - 1)
overall_accuracy_row_svm = pd.Series(overall_accuracy_data_svm, index=svm_cm_df.columns, name='Overall_Accuracy')
svm_cm_df = pd.concat([svm_cm_df, overall_accuracy_row_svm.to_frame().T])

# Add Overall Precision as a new row
precision_data_svm = [SVM_Precision] + [np.nan] * (len(svm_cm_df.columns) - 1)
precision_row_svm = pd.Series(precision_data_svm, index=svm_cm_df.columns, name='Overall_Precision')
svm_cm_df = pd.concat([svm_cm_df, precision_row_svm.to_frame().T])

# Add Overall Recall as a new row
recall_data_svm = [SVM_recall] + [np.nan] * (len(svm_cm_df.columns) - 1)
recall_row_svm = pd.Series(recall_data_svm, index=svm_cm_df.columns, name='Overall_Recall')
svm_cm_df = pd.concat([svm_cm_df, recall_row_svm.to_frame().T])

# Add F1-score as a new row
f1_score_data_svm = [SVM_F1] + [np.nan] * (len(svm_cm_df.columns) - 1)
f1_score_row_svm = pd.Series(f1_score_data_svm, index=svm_cm_df.columns, name='F1_Score')
svm_cm_df = pd.concat([svm_cm_df, f1_score_row_svm.to_frame().T])

svm_cm_df.to_csv(f"{output_folder}/svm confusion matrix.csv")
print(f"SVM Confusion Matrix with accuracies exported to {output_folder}/svm_confusion_matrix_with_accuracies.csv")

# --- Random Forest Confusion Matrix with Accuracies ---
rf_cm_df = pd.DataFrame(RF_confusion_matrix, index=class_names, columns=class_names)

# Add Producer's Accuracy as a new column
rf_cm_df['Producer_Accuracy'] = pd.Series(RF_PA, index=class_names)

# Add User's Accuracy as a new row, filling non-applicable columns with NaN
user_accuracy_row_rf = pd.Series(RF_UA, index=class_names, name='User_Accuracy')
user_accuracy_row_extended_rf = user_accuracy_row_rf.reindex(rf_cm_df.columns, fill_value=np.nan)
rf_cm_df = pd.concat([rf_cm_df, user_accuracy_row_extended_rf.to_frame().T])

# Add Overall Accuracy as a new row, filling non-applicable columns with NaN
overall_accuracy_data_rf = [RF_OA] + [np.nan] * (len(rf_cm_df.columns) - 1)
overall_accuracy_row_rf = pd.Series(overall_accuracy_data_rf, index=rf_cm_df.columns, name='Overall_Accuracy')
rf_cm_df = pd.concat([rf_cm_df, overall_accuracy_row_rf.to_frame().T])

# Add Overall Precision as a new row
precision_data_rf = [RF_Precision] + [np.nan] * (len(rf_cm_df.columns) - 1)
precision_row_rf = pd.Series(precision_data_rf, index=rf_cm_df.columns, name='Overall_Precision')
rf_cm_df = pd.concat([rf_cm_df, precision_row_rf.to_frame().T])

# Add Overall Recall as a new row
recall_data_rf = [RF_recall] + [np.nan] * (len(rf_cm_df.columns) - 1)
recall_row_rf = pd.Series(recall_data_rf, index=rf_cm_df.columns, name='Overall_Recall')
rf_cm_df = pd.concat([rf_cm_df, recall_row_rf.to_frame().T])

# Add F1-score as a new row
f1_score_data_rf = [RF_F1] + [np.nan] * (len(rf_cm_df.columns) - 1)
f1_score_row_rf = pd.Series(f1_score_data_rf, index=rf_cm_df.columns, name='F1_Score')
rf_cm_df = pd.concat([rf_cm_df, f1_score_row_rf.to_frame().T])

rf_cm_df.to_csv(f"{output_folder}/RF confusion matrix.csv")
print(f"Random Forest Confusion Matrix with accuracies exported to {output_folder}/rf_confusion_matrix_with_accuracies.csv")

# --- KNN Confusion Matrix with Accuracies ---
knn_cm_df = pd.DataFrame(KNN_confusion_matrix, index=class_names, columns=class_names)

# Add Producer's Accuracy as a new column
knn_cm_df['Producer_Accuracy'] = pd.Series(KNN_PA, index=class_names)

# Add User's Accuracy as a new row, filling non-applicable columns with NaN
user_accuracy_row_knn = pd.Series(KNN_UA, index=class_names, name='User_Accuracy')
user_accuracy_row_extended_knn = user_accuracy_row_knn.reindex(knn_cm_df.columns, fill_value=np.nan)
knn_cm_df = pd.concat([knn_cm_df, user_accuracy_row_extended_knn.to_frame().T])

# Add Overall Accuracy as a new row, filling non-applicable columns with NaN
overall_accuracy_data_knn = [KNN_OA] + [np.nan] * (len(knn_cm_df.columns) - 1)
overall_accuracy_row_knn = pd.Series(overall_accuracy_data_knn, index=knn_cm_df.columns, name='Overall_Accuracy')
knn_cm_df = pd.concat([knn_cm_df, overall_accuracy_row_knn.to_frame().T])

# Add Overall Precision as a new row
precision_data_knn = [KNN_Precision] + [np.nan] * (len(knn_cm_df.columns) - 1)
precision_row_knn = pd.Series(precision_data_knn, index=knn_cm_df.columns, name='Overall_Precision')
knn_cm_df = pd.concat([knn_cm_df, precision_row_knn.to_frame().T])

# Add Overall Recall as a new row
recall_data_knn = [KNN_recall] + [np.nan] * (len(knn_cm_df.columns) - 1)
recall_row_knn = pd.Series(recall_data_knn, index=knn_cm_df.columns, name='Overall_Recall')
knn_cm_df = pd.concat([knn_cm_df, recall_row_knn.to_frame().T])

# Add F1-score as a new row
f1_score_data_knn = [KNN_F1] + [np.nan] * (len(knn_cm_df.columns) - 1)
f1_score_row_knn = pd.Series(f1_score_data_knn, index=knn_cm_df.columns, name='F1_Score')
knn_cm_df = pd.concat([knn_cm_df, f1_score_row_knn.to_frame().T])

knn_cm_df.to_csv(f"{output_folder}/KNN confusion matrix.csv")
print(f"KNN Confusion Matrix with accuracies exported to {output_folder}/knn_confusion_matrix_with_accuracies.csv")

SVM Confusion Matrix with accuracies exported to /content/drive/MyDrive/Colab Notebooks/PhD Data/Sentinel 2/svm_confusion_matrix_with_accuracies.csv
Random Forest Confusion Matrix with accuracies exported to /content/drive/MyDrive/Colab Notebooks/PhD Data/Sentinel 2/rf_confusion_matrix_with_accuracies.csv
KNN Confusion Matrix with accuracies exported to /content/drive/MyDrive/Colab Notebooks/PhD Data/Sentinel 2/knn_confusion_matrix_with_accuracies.csv


## Export classified result

In [ ]:
# Class labels and corresponding values
print("Mapping of numerical labels to original class names:")
for i, name in enumerate(class_names):
    print(f"Numerical Value {i}: {name}")

Mapping of numerical labels to original class names:
Numerical Value 0: Developed Areas
Numerical Value 1: Mining
Numerical Value 2: Cocoa plots
Numerical Value 3: Forest
Numerical Value 4: Crop land
Numerical Value 5: Water


**SVM classified image**

In [ ]:
svm_task = ee.batch.Export.image.toDrive(**{
    'image': svm_classified_image.toFloat(), # Cast to float to ensure compatible data types
    'description': 'SVM Classified Image for Western Ghana',
    'folder': "Sentinel 2",
    'fileNamePrefix': 'svm_classified_S2WG',
    'region': AOI.geometry(),
    'scale': 10,
    'crs': 'EPSG:4326', # Standard coordinate system (WGS84)
    'fileFormat': 'GeoTIFF',
    'maxPixels': 1e10  # Increase maxPixels to allow exporting larger areas
})

# Start the task
svm_task.start()

**RF Classified image**

In [ ]:
rf_task = ee.batch.Export.image.toDrive(**{
    'image': rf_classified_image.toFloat(), # Export the RF classified image
    'description': 'Random Forest Classified Image for Western Ghana',
    'folder': "Sentinel 2",
    'fileNamePrefix': 'rf_classified_S2WG',
    'region': AOI.geometry(),
    'scale': 10,
    'crs': 'EPSG:4326',
    'fileFormat': 'GeoTIFF',
    'maxPixels': 1e10
})

# Start the task
rf_task.start()
print(rf_task.status())

{'state': 'READY', 'description': 'Random Forest Classified Image for Western Ghana', 'priority': 100, 'creation_timestamp_ms': 1770997183089, 'update_timestamp_ms': 1770997183089, 'start_timestamp_ms': 0, 'task_type': 'EXPORT_IMAGE', 'id': 'OFGFNI67KLJHBG2CL42DLJRO', 'name': 'projects/ee-abutunghem/operations/OFGFNI67KLJHBG2CL42DLJRO'}


**KNN Classified image**

In [ ]:
knn_task = ee.batch.Export.image.toDrive(**{
    'image': knn_classified_image.toFloat(), # Export the KNN classified image
    'description': 'KNN Classified Image for Western Ghana',
    'folder': "Sentinel 2",
    'fileNamePrefix': 'knn_classified_S2WG',
    'region': AOI.geometry(),
    'scale': 10,
    'crs': 'EPSG:4326',
    'fileFormat': 'GeoTIFF',
    'maxPixels': 1e10
})

# Start the task
knn_task.start()

In [ ]:
# Check the status of the export task
print(svm_task.status(), rf_task.status(), knn_task.status())

{'state': 'RUNNING', 'description': 'SVM Classified Image for Western Ghana', 'priority': 100, 'creation_timestamp_ms': 1770997142978, 'update_timestamp_ms': 1770997892340, 'start_timestamp_ms': 1770997149470, 'task_type': 'EXPORT_IMAGE', 'attempt': 1, 'batch_eecu_usage_seconds': 4063.696, 'id': 'IOBLJCJYJWUVTSAJOTRQ3NDI', 'name': 'projects/ee-abutunghem/operations/IOBLJCJYJWUVTSAJOTRQ3NDI'} {'state': 'RUNNING', 'description': 'Random Forest Classified Image for Western Ghana', 'priority': 100, 'creation_timestamp_ms': 1770997183089, 'update_timestamp_ms': 1770997893680, 'start_timestamp_ms': 1770997185142, 'task_type': 'EXPORT_IMAGE', 'attempt': 1, 'batch_eecu_usage_seconds': 621.457, 'id': 'OFGFNI67KLJHBG2CL42DLJRO', 'name': 'projects/ee-abutunghem/operations/OFGFNI67KLJHBG2CL42DLJRO'} {'state': 'READY', 'description': 'KNN Classified Image for Western Ghana', 'priority': 100, 'creation_timestamp_ms': 1770997183886, 'update_timestamp_ms': 1770997747007, 'start_timestamp_ms': 17709977

## Export filtered images
This is an optional section that is aimed at exporting the filtered mosiac images for visualisation in RS and GIS software